all:
  vars:
    ansible_user: ansible
  hosts:
    ad42e8b2fa7d4a3dbc5aecef7810a624:
      ansible_host: 192.168.0.21
      docker_volume_backups:
        - source_volume_name: codekaizen_website_wordpress_db_data
          host_dest_file_path: "/tmp/docker_volume_backup.tar.gz"
          local_dest_file_path: "/tmp/docker_volume_backup.tar.gz"
